name: Test

on:
  push:
    paths-ignore:
    - '.git**'
    - '**.md'
    - 'LICENSE'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        exclude:
        - os: windows-latest
          feature-tls: tls-openssl
        os: [ubuntu-latest, windows-latest]
        rust: [1.88.0, stable]
        feature-crypto: [aws-lc-rs, rust-crypto]
        feature-tls: [tls-openssl, tls-rustls]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Cache Cargo
      uses: actions/cache@v6
      with:
        path: |
          '~/.cargo'
          './target'
        key: ${{ matrix.os }}-cargo-${{ matrix.rust }}_${{ matrix.feature-crypto }}_${{ matrix.feature-tls }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ matrix.os }}-cargo-${{ matrix.rust }}_${{ matrix.feature-crypto }}_${{ matrix.feature-tls }}-

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Run test
      run: |
        cargo test --no-default-features --features ${{ matrix.feature-crypto }},${{ matrix.feature-tls }}
