name: Test

on:
  push:
    paths-ignore:
      - '.git**'
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-crypto: [aws-lc-rs, rust-crypto]
        feature-tls: [tls-openssl, tls-rustls]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache Cargo
        uses: actions/cache@v6
        with:
          path: |
            '~/.cargo'
            './target'
          key: cargo-${{ matrix.feature-crypto }}_${{ matrix.feature-tls }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: cargo-${{ matrix.feature-crypto }}_${{ matrix.feature-tls }}-

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run test
        run: |
          cargo test --no-default-features --features ${{ matrix.feature-crypto }},${{ matrix.feature-tls }}
